### ISSUE TITLE
Finder as a popup morph

### ISSUE THREAD

**Issue by mmontone** [npapagna/cuis-finder#1]
Hello Nicolas!

I've made some changes to the finder.

I've made it so that:

* Make it a Morph, not a window.
* Opens at the center of the screen.
* Is triggered either by Shift+Enter, but also when you just start typing when PastUpMorph (background morph) has focus (that is to say, when no other text morph has focus).

Work is in FinderMorph class.

Can you try it an give me your opinion:?

https://github.com/mmontone/Cuis-Smalltalk-Dev/releases/tag/finder-0.0.1

(I attach only some Smalltalk images for now...)

And if you like it, we can try to integrate.

Thanks!

Mariano

**Comment by mmontone** [comment]
![imagen](https://user-images.githubusercontent.com/436110/92404229-6cc3ea80-f109-11ea-9e11-17ef32afa14c.png)

**Comment by mmontone** [comment]
I also added ability to navigate catalogs using left and right arrow. 

Like this:

```smalltalk
processArrowLeftOrRight: aKeyboardEvent 
	
	aKeyboardEvent isArrowLeft 
		ifTrue: [ 
			model selectPreviousCatalog.
			^ true ].
		
	aKeyboardEvent isArrowRight 
		ifTrue: [ 
			model selectNextCatalog.
			^ true ].

	^ false
```

This is not in the attached images, but is part of what I'd like to change.

**Comment by npapagna** [comment]
Wow, this looks really good, thanks Mariano!

I will definitely give it a try in the next days and let you know.

Thanks :)
Nico

**Comment by mmontone** [comment]
I've updated the images, so you can try catalog navigation via arrows now too.
